let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
  {
    id: "bvkjbdbdk",
    name: "Watermelon",
    price: 45,
    desc: "Watermelon 2 kg.",
    img: "images/img-13.jpg",
  },
  {
    id: "nsdlsifsdb",
    name: "Onion",
    price: 100,
    desc: "Onion 1 kg.",
    img: "images/img-14.jpg",
  },
  {
    id: "lsdfoeprjw",
    name: "Orange",
    price: 25,
    desc: "Orange Royal Gala 1 kg.",
    img: "images/img-15.jpg",
  },
  {
    id: "fdksbfoeeoihihr",
    name: "Tender Coconut",
    price: 300,
    desc: "Tender Coconut Cling Wrapped (1 pc) (Approx 900 g - 1300 g).",
    img: "images/img-16.jpg",
  },
  {
    id: "jbjjksbguri",
    name: "Ginger",
    price: 45,
    desc: "Ginger Indian 200 g.",
    img: "images/img-17.jpg",
  },
  {
    id: "vsbdirugi",
    name: "Green Tea",
    price: 100,
    desc: "Nilgiri Whole Leaf Green Tea 100 Gm.",
    img: "images/img-18.jpg",
  },
  {
    id: "ituoweebeio",
    name: "Red Label",
    price: 25,
    desc: "Brooke Bond Red Label Strong Blend Tea 1 kg.",
    img: "images/img-19.jpg",
  },
  {
    id: "etpwurweuiht",
    name: "Slice",
    price: 300,
    desc: "Slice 2.25 L.",
    img: "images/img-20.jpg",
  },
  {
    id: "gsirohhtwtto",
    name: "7Up",
    price: 45,
    desc: "7Up 2.25 L.",
    img: "images/img-21.jpg",
  },
  {
    id: "gbtetothoew",
    name: "Coconut Powder",
    price: 100,
    desc: "Classic Harvest Dessicated Coconut Powder , Nariyal Burada, Coconut Powder, Dry Coconut Powder 500g.",
    img: "images/img-22.jpg",
  },
  {
    id: "pkonrihbsohfiht",
    name: "Sunflower Oil",
    price: 25,
    desc: "Gold Winner Refined Sunflower Oil 1 L (Pouch).",
    img: "images/img-23.jpg",
  },
  {
    id: "sgfjhieotoreuh",
    name: "Mixer Grinder",
    price: 300,
    desc: "Lifelong Infinia 500 Watts Mixer Grinder, Grey.",
    img: "images/img-24.jpg",
  },
  {
    id: "deuruireiu",
    name: "Ceiling Fan",
    price: 45,
    desc: "ZunVolt Thundermax High Speed 1200 mm (48 inch) 3 Blade Ceiling Fan, Brown.",
    img: "images/img-25.jpg",
  },
  {
    id: "irorttuyhgdi",
    name: "Electric Tea Kettle",
    price: 100,
    desc: "Padmashree 1500W 1.8L Electric Tea Kettle with Auto-Shutoff and Boil-Dry Protection, Silver.",
    img: "images/img-26.jpg",
  },

];
